CAT0:
  - '\[A11Y\]'
  - '(\[x\] Blocker|\[x\] Critical|\[x\] Serious)'
CAT2:
  - '\[A11Y\]'
  - '\[x\] Moderate'
BLOCKER:
  - '\[A11Y\]'
  - '\[x\] Blocker'
CRITICAL:
  - '\[A11Y\]'
  - '\[x\] Critical'
SERIOUS:
  - '\[A11Y\]'
  - '\[x\] Serious'
MODERATE:
  - '\[A11Y\]'
  - '\[x\] Moderate'
MIOR:
  - '\[A11Y\]'
  - '\[x\] Minor'
CUSTOMER:
  - '\[A11Y\]'
  - '\[x\] Found by Customer'
VPAT:
  - '\[A11Y\]'
  - '\[x\] Found in VPAT'
WCAG 1.1.1:
  - '\[A11Y\]'
  - '(\[x\] 1.1.1 Non-text Content|1.1.1 Non-text Content \[x\])'
WCAG 1.2.1:
  - '\[A11Y\]'
  - '(\[x\] 1.2.1 Audio-only and Video-only \(Prerecorded\)|1.2.1 Audio-only and Video-only \(Prerecorded\) \[x\])'
WCAG 1.2.2:
  - '\[A11Y\]'
  - '(\[x\] 1.2.2 Captions \(Prerecorded\)|1.2.2 Captions \(Prerecorded\) \[x\])'
WCAG 1.2.3:
  - '\[A11Y\]'
  - '(\[x\] 1.2.3 Audio Description or Media Alternative \(Prerecorded\)|1.2.3 Audio Description or Media Alternative \(Prerecorded\) \[x\])'
WCAG 1.2.4:
  - '\[A11Y\]'
  - '(\[x\] 1.2.4 Captions \(Live\)|1.2.4 Captions \(Live\) \[x\])'
WCAG 1.2.5:
  - '\[A11Y\]'
  - '(\[x\] 1.2.5 Audio Description \(Prerecorded\)|1.2.5 Audio Description \(Prerecorded\) \[x\])'
WCAG 1.2.6:
  - '\[A11Y\]'
  - '(\[x\] 1.2.6 Sign Language \(Prerecorded\)|1.2.6 Sign Language \(Prerecorded\) \[x\])'
WCAG 1.2.7:
  - '\[A11Y\]'
  - '(\[x\] 1.2.7 Extended Audio Description \(Prerecorded\)|1.2.7 Extended Audio Description \(Prerecorded\) \[x\])'
WCAG 1.2.8:
  - '\[A11Y\]'
  - '(\[x\] 1.2.8 Media Alternative \(Prerecorded\)|1.2.8 Media Alternative \(Prerecorded\) \[x\])'
WCAG 1.2.9:
  - '\[A11Y\]'
  - '(\[x\] 1.2.9 Audio-only \(Live\)|1.2.9 Audio-only \(Live\) \[x\])'
WCAG 1.3.1:
  - '\[A11Y\]'
  - '(\[x\] 1.3.1 Info and Relationships|1.3.1 Info and Relationships \[x\])'
WCAG 1.3.2:
  - '\[A11Y\]'
  - '(\[x\] 1.3.2 Meaningful Sequence|1.3.2 Meaningful Sequence \[x\])'
WCAG 1.3.3:
  - '\[A11Y\]'
  - '(\[x\] 1.3.3 Sensory Characteristics|1.3.3 Sensory Characteristics \[x\])'
WCAG 1.3.4:
  - '\[A11Y\]'
  - '(\[x\] 1.3.4 Orientation|1.3.4 Orientation \[x\])'
WCAG 1.3.5:
  - '\[A11Y\]'
  - '(\[x\] 1.3.5 Identify Input Purpose|1.3.5 Identify Input Purpose \[x\])'
WCAG 1.3.6:
  - '\[A11Y\]'
  - '(\[x\] 1.3.6 Identify Purpose|1.3.6 Identify Purpose \[x\])'
WCAG 1.4.1:
  - '\[A11Y\]'
  - '(\[x\] 1.4.1 Use of Color|1.4.1 Use of Color \[x\])'
WCAG 1.4.2:
  - '\[A11Y\]'
  - '(\[x\] 1.4.2 Audio Control|1.4.2 Audio Control \[x\])'
WCAG 1.4.3:
  - '\[A11Y\]'
  - '(\[x\] 1.4.3 Contrast (Minimum)|1.4.3 Contrast (Minimum) \[x\])'
WCAG 1.4.4:
  - '\[A11Y\]'
  - '(\[x\] 1.4.4 Resize text|1.4.4 Resize text \[x\])'
WCAG 1.4.5:
  - '\[A11Y\]'
  - '(\[x\] 1.4.5 Images of Text|1.4.5 Images of Text \[x\])'
WCAG 1.4.6:
  - '\[A11Y\]'
  - '(\[x\] 1.4.6 Contrast (Enhanced)|1.4.6 Contrast (Enhanced) \[x\])'
WCAG 1.4.7:
  - '\[A11Y\]'
  - '(\[x\] 1.4.7 Low or No Background Audio|1.4.7 Low or No Background Audio \[x\])'
WCAG 1.4.8:
  - '\[A11Y\]'
  - '(\[x\] 1.4.8 Visual Presentation|1.4.8 Visual Presentation \[x\])'
WCAG 1.4.9:
  - '\[A11Y\]'
  - '(\[x\] 1.4.9 Images of Text (No Exception)|1.4.9 Images of Text (No Exception) \[x\])'
WCAG 1.4.10:
  - '\[A11Y\]'
  - '(\[x\] 1.4.10 Reflow|1.4.10 Reflow \[x\])'
WCAG 1.4.11:
  - '\[A11Y\]'
  - '(\[x\] 1.4.11 Non-text Contrast|1.4.11 Non-text Contrast \[x\])'
WCAG 1.4.12:
  - '\[A11Y\]'
  - '(\[x\] 1.4.12 Text Spacing|1.4.12 Text Spacing \[x\])'
WCAG 1.4.13:
  - '\[A11Y\]'
  - '(\[x\] 1.4.13 Content on Hover or Focus|1.4.13 Content on Hover or Focus \[x\])'
WCAG 2.1.1:
  - '\[A11Y\]'
  - '(\[x\] 2.1.1 Keyboard|2.1.1 Keyboard \[x\])'
WCAG 2.1.2:
  - '\[A11Y\]'
  - '(\[x\] 2.1.2 No Keyboard Trap|2.1.2 No Keyboard Trap \[x\])'
WCAG 2.1.3:
  - '\[A11Y\]'
  - '(\[x\] 2.1.3 Keyboard (No Exception)|2.1.3 Keyboard (No Exception) \[x\])'
WCAG 2.1.4:
  - '\[A11Y\]'
  - '(\[x\] 2.1.4 Character Key Shortcuts|2.1.4 Character Key Shortcuts \[x\])'
WCAG 2.2.1:
  - '\[A11Y\]'
  - '(\[x\] 2.2.1 Timing Adjustable|2.2.1 Timing Adjustable \[x\])'
WCAG 2.2.2:
  - '\[A11Y\]'
  - '(\[x\] 2.2.2 Pause, Stop, Hide|2.2.2 Pause, Stop, Hide \[x\])'
WCAG 2.2.3:
  - '\[A11Y\]'
  - '(\[x\] 2.2.3 No Timing|2.2.3 No Timing \[x\])'
WCAG 2.2.4:
  - '\[A11Y\]'
  - '(\[x\] 2.2.4 Interruptions|2.2.4 Interruptions \[x\])'
WCAG 2.2.5:
  - '\[A11Y\]'
  - '(\[x\] 2.2.5 Re-authenticating|2.2.5 Re-authenticating \[x\])'
WCAG 2.2.6:
  - '\[A11Y\]'
  - '(\[x\] 2.2.6 Timeouts|2.2.6 Timeouts \[x\])'
WCAG 2.3.1:
  - '\[A11Y\]'
  - '(\[x\] 2.3.1 Three Flashes or Below Threshold|2.3.1 Three Flashes or Below Threshold \[x\])'
WCAG 2.3.2:
  - '\[A11Y\]'
  - '(\[x\] 2.3.2 Three Flashes|2.3.2 Three Flashes \[x\])'
WCAG 2.3.3:
  - '\[A11Y\]'
  - '(\[x\] 2.3.3 Animation from Interactions|2.3.3 Animation from Interactions \[x\])'
WCAG 2.4.1:
  - '\[A11Y\]'
  - '(\[x\] 2.4.1 Bypass Blocks|2.4.1 Bypass Blocks \[x\])'
WCAG 2.4.2:
  - '\[A11Y\]'
  - '(\[x\] 2.4.2 Page Titled|2.4.2 Page Titled \[x\])'
WCAG 2.4.3:
  - '\[A11Y\]'
  - '(\[x\] 2.4.3 Focus Order|2.4.3 Focus Order \[x\])'
WCAG 2.4.4:
  - '\[A11Y\]'
  - '(\[x\] 2.4.4 Link Purpose \(In Context\)|2.4.4 Link Purpose \(In Context\) \[x\])'
WCAG 2.4.5:
  - '\[A11Y\]'
  - '(\[x\] 2.4.5 Multiple Ways|2.4.5 Multiple Ways \[x\])'
WCAG 2.4.6:
  - '\[A11Y\]'
  - '(\[x\] 2.4.6 Headings and Labels|2.4.6 Headings and Labels \[x\])'
WCAG 2.4.7:
  - '\[A11Y\]'
  - '(\[x\] 2.4.7 Focus Visible|2.4.7 Focus Visible \[x\])'
WCAG 2.4.8:
  - '\[A11Y\]'
  - '(\[x\] 2.4.8 Location|2.4.8 Location \[x\])'
WCAG 2.4.9:
  - '\[A11Y\]'
  - '(\[x\] 2.4.9 Link Purpose (Link Only)|2.4.9 Link Purpose (Link Only) \[x\])'
WCAG 2.4.10:
  - '\[A11Y\]'
  - '(\[x\] 2.4.10 Section Headings|2.4.10 Section Headings \[x\])'
WCAG 2.5.1:
  - '\[A11Y\]'
  - '(\[x\] 2.5.1 Pointer Gestures|2.5.1 Pointer Gestures \[x\])'
WCAG 2.5.2:
  - '\[A11Y\]'
  - '(\[x\] 2.5.2 Pointer Cancellation|2.5.2 Pointer Cancellation \[x\])'
WCAG 2.5.3:
  - '\[A11Y\]'
  - '(\[x\] 2.5.3 Label in Name|2.5.3 Label in Name \[x\])'
WCAG 2.5.4:
  - '\[A11Y\]'
  - '(\[x\] 2.5.4 Motion Actuation|2.5.4 Motion Actuation \[x\])'
WCAG 2.5.5:
  - '\[A11Y\]'
  - '(\[x\] 2.5.5 Target Size|2.5.5 Target Size \[x\])'
WCAG 2.5.6:
  - '\[A11Y\]'
  - '(\[x\] 2.5.6 Concurrent Input Mechanisms|2.5.6 Concurrent Input Mechanisms \[x\])'
WCAG 3.1.1:
  - '\[A11Y\]'
  - '(\[x\] 3.1.1 Language of Page|3.1.1 Language of Page \[x\])'
WCAG 3.1.2:
  - '\[A11Y\]'
  - '(\[x\] 3.1.2 Language of Parts|3.1.2 Language of Parts \[x\])'
WCAG 3.1.3:
  - '\[A11Y\]'
  - '(\[x\] 3.1.3 Unusual Words|3.1.3 Unusual Words \[x\])'
WCAG 3.1.4:
  - '\[A11Y\]'
  - '(\[x\] 3.1.4 Abbreviations|3.1.4 Abbreviations \[x\])'
WCAG 3.1.5:
  - '\[A11Y\]'
  - '(\[x\] 3.1.5 Reading Level|3.1.5 Reading Level \[x\])'
WCAG 3.1.6:
  - '\[A11Y\]'
  - '(\[x\] 3.1.6 Pronunciation|3.1.6 Pronunciation \[x\])'
WCAG 3.2.1:
  - '\[A11Y\]'
  - '(\[x\] 3.2.1 On Focus|3.2.1 On Focus \[x\])'
WCAG 3.2.2:
  - '\[A11Y\]'
  - '(\[x\] 3.2.2 On Input|3.2.2 On Input \[x\])'
WCAG 3.2.3:
  - '\[A11Y\]'
  - '(\[x\] 3.2.3 Consistent Navigation|3.2.3 Consistent Navigation \[x\])'
WCAG 3.2.4:
  - '\[A11Y\]'
  - '(\[x\] 3.2.4 Consistent Identification|3.2.4 Consistent Identification \[x\])'
WCAG 3.2.5:
  - '\[A11Y\]'
  - '(\[x\] 3.2.5 Change on Request|3.2.5 Change on Request \[x\])'
WCAG 3.3.1:
  - '\[A11Y\]'
  - '(\[x\] 3.3.1 Error Identification|3.3.1 Error Identification \[x\])'
WCAG 3.3.2:
  - '\[A11Y\]'
  - '(\[x\] 3.3.2 Labels or Instructions|3.3.2 Labels or Instructions \[x\])'
WCAG 3.3.3:
  - '\[A11Y\]'
  - '(\[x\] 3.3.3 Error Suggestion|3.3.3 Error Suggestion \[x\])'
WCAG 3.3.4:
  - '\[A11Y\]'
  - '(\[x\] 3.3.4 Error Prevention \(Legal, Financial, Data\)|3.3.4 Error Prevention \(Legal, Financial, Data\) \[x\])'
WCAG 3.3.5:
  - '\[A11Y\]'
  - '(\[x\] 3.3.5 Help|3.3.5 Help \[x\])'
WCAG 3.3.6:
  - '\[A11Y\]'
  - '(\[x\] 3.3.6 Error Prevention \(All\)|3.3.6 Error Prevention \(All\) \[x\])'
WCAG 4.1.1:
  - '\[A11Y\]'
  - '(\[x\] 4.1.1 Parsing|4.1.1 Parsing \[x\])'
WCAG 4.1.2:
  - '\[A11Y\]'
  - '(\[x\] 4.1.2 Name, Role, Value|4.1.2 Name, Role, Value \[x\])'
WCAG 4.1.3:
  - '\[A11Y\]'
  - '(\[x\] 4.1.3 Status Messages|4.1.3 Status Messages \[x\])'