CAT0:
  - '(cat0|CAT0|Cat0|[x] Blocker|[x] Critical|[x] Serious)'
CAT1:
  - '(cat1|CAT1|Cat1)'
CAT2:
  - '(cat2|CAT2|Cat2|\[x\] Moderate)'
CAT3:
  - '(cat3|CAT3|Cat3)'
CAT4:
  - '(cat4|CAT4|Cat4)'
VPAT:
  - '\[x\] Found in VPAT'
wcag1.1.1:
  - '\[x\] 1.1.1 Non-text Content'
wcag1.2.1:
  - '\[x\] 1.2.1 Audio-only and Video-only \(Prerecorded\)'
wcag1.2.2:
  - '\[x\] 1.2.2 Captions \(Prerecorded\)'
wcag1.2.3:
  - '\[x\] 1.2.3 Audio Description or Media Alternative \(Prerecorded\)'
wcag1.2.4:
  - '\[x\] 1.2.4 Captions \(Live\)'
wcag1.2.5:
  - '\[x\] 1.2.5 Audio Description \(Prerecorded\)'
wcag1.2.6:
  - '\[x\] 1.2.6 Sign Language \(Prerecorded\)'
wcag1.2.7:
  - '\[x\] 1.2.7 Extended Audio Description \(Prerecorded\)'
wcag1.2.8:
  - '\[x\] 1.2.8 Media Alternative \(Prerecorded\)'
wcag1.2.9:
  - '\[x\] 1.2.9 Audio-only \(Live\)'
wcag1.3.1:
  - '\[x\] 1.3.1 Info and Relationships'
wcag1.3.2:
  - '\[x\] 1.3.2 Meaningful Sequence'
wcag1.3.3:
  - '\[x\] 1.3.3 Sensory Characteristics'
wcag1.3.4:
  - '\[x\] 1.3.4 Orientation'
wcag1.3.5:
  - '\[x\] 1.3.5 Identify Input Purpose'
wcag1.3.6:
  - '\[x\] 1.3.6 Identify Purpose'
wcag1.4.1:
  - '\[x\] 1.4.1 Use of Color'
wcag1.4.2:
  - '\[x\] 1.4.2 Audio Control'
wcag1.4.3:
  - '\[x\] 1.4.3 Contrast (Minimum)'
wcag1.4.4:
  - '\[x\] 1.4.4 Resize text'
wcag1.4.5:
  - '\[x\] 1.4.5 Images of Text'
wcag1.4.6:
  - '\[x\] 1.4.6 Contrast (Enhanced)'
wcag1.4.7:
  - '\[x\] 1.4.7 Low or No Background Audio'
wcag1.4.8:
  - '\[x\] 1.4.8 Visual Presentation'
wcag1.4.9:
  - '\[x\] 1.4.9 Images of Text (No Exception)'
wcag1.4.10:
  - '\[x\] 1.4.10 Reflow'
wcag1.4.11:
  - '\[x\] 1.4.11 Non-text Contrast'
wcag1.4.12:
  - '\[x\] 1.4.12 Text Spacing'
wcag1.4.13:
  - '\[x\] 1.4.13 Content on Hover or Focus'
wcag2.1.1:
  - '\[x\] 2.1.1 Keyboard'
wcag2.1.2:
  - '\[x\] 2.1.2 No Keyboard Trap'
wcag2.1.3:
  - '\[x\] 2.1.3 Keyboard (No Exception)'
wcag2.1.4:
  - '\[x\] 2.1.4 Character Key Shortcuts'
wcag2.2.1:
  - '\[x\] 2.2.1 Timing Adjustable'
wcag2.2.2:
  - '\[x\] 2.2.2 Pause, Stop, Hide'
wcag2.2.3:
  - '\[x\] 2.2.3 No Timing'
wcag2.2.4:
  - '\[x\] 2.2.4 Interruptions'
wcag2.2.5:
  - '\[x\] 2.2.5 Re-authenticating'
wcag2.2.6:
  - '\[x\] 2.2.6 Timeouts'
wcag2.3.1:
  - '\[x\] 2.3.1 Three Flashes or Below Threshold'
wcag2.3.2:
  - '\[x\] 2.3.2 Three Flashes'
wcag2.3.3:
  - '\[x\] 2.3.3 Animation from Interactions'
wcag2.4.1:
  - '\[x\] 2.4.1 Bypass Blocks'
wcag2.4.2:
  - '\[x\] 2.4.2 Page Titled'
wcag2.4.3:
  - '\[x\] 2.4.3 Focus Order'
wcag2.4.4:
  - '\[x\] 2.4.4 Link Purpose (In Context)'
wcag2.4.5:
  - '\[x\] 2.4.5 Multiple Ways'
wcag2.4.6:
  - '\[x\] 2.4.6 Headings and Labels'
wcag2.4.7:
  - '\[x\] 2.4.7 Focus Visible'
wcag2.4.8:
  - '\[x\] 2.4.8 Location'
wcag2.4.9:
  - '\[x\] 2.4.9 Link Purpose (Link Only)'
wcag2.4.10:
  - '\[x\] 2.4.10 Section Headings'
wcag2.5.1:
  - '\[x\] 2.5.1 Pointer Gestures'
wcag2.5.2:
  - '\[x\] 2.5.2 Pointer Cancellation'
wcag2.5.3:
  - '\[x\] 2.5.3 Label in Name'
wcag2.5.4:
  - '\[x\] 2.5.4 Motion Actuation'
wcag2.5.5:
  - '\[x\] 2.5.5 Target Size'
wcag2.5.6:
  - '\[x\] 2.5.6 Concurrent Input Mechanisms'
wcag3.1.1:
  - '\[x\] 3.1.1 Language of Page'
wcag3.1.2:
  - '\[x\] 3.1.2 Language of Parts'
wcag3.1.3:
  - '\[x\] 3.1.3 Unusual Words'
wcag3.1.4:
  - '\[x\] 3.1.4 Abbreviations'
wcag3.1.5:
  - '\[x\] 3.1.5 Reading Level'
wcag3.1.6:
  - '\[x\] 3.1.6 Pronunciation'
wcag3.2.1:
  - '\[x\] 3.2.1 On Focus'
wcag3.2.2:
  - '\[x\] 3.2.2 On Input'
wcag3.2.3:
  - '\[x\] 3.2.3 Consistent Navigation'
wcag3.2.4:
  - '\[x\] 3.2.4 Consistent Identification'
wcag3.2.5:
  - '\[x\] 3.2.5 Change on Request'
wcag3.3.1:
  - '\[x\] 3.3.1 Error Identification'
wcag3.3.2:
  - '\[x\] 3.3.2 Labels or Instructions'
wcag3.3.3:
  - '\[x\] 3.3.3 Error Suggestion'
wcag3.3.4:
  - '\[x\] 3.3.4 Error Prevention (Legal, Financial, Data)'
wcag3.3.5:
  - '\[x\] 3.3.5 Help'
wcag3.3.6:
  - '\[x\] 3.3.6 Error Prevention (All)'
wcag4.1.1:
  - '\[x\] 4.1.1 Parsing'
wcag4.1.2:
  - '\[x\] 4.1.2 Name, Role, Value'
wcag4.1.3:
  - '\[x\] 4.1.3 Status Messages'